# Generated by Django 5.1.2 on 2024-11-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('max_score', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('group_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_format', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('code', 'Code')], max_length=10)),
                ('description', models.TextField()),
                ('has_time_limit', models.BooleanField(default=False)),
                ('has_upload_limit', models.BooleanField(default=False)),
                ('first_deadline', models.DateTimeField(blank=True, null=True)),
                ('second_deadline', models.DateTimeField(blank=True, null=True)),
                ('penalty_hour', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('upload_limit', models.IntegerField(blank=True, null=True)),
                ('in_bank', models.BooleanField(default=False)),
                ('max_score', models.IntegerField(default=100)),
                ('is_team', models.BooleanField(default=False)),
                ('scoring_way', models.IntegerField(default=0)),
                ('num_students_in_each_team', models.IntegerField(blank=True, default=1, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercise.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_score', models.IntegerField(blank=True, null=True)),
                ('manual_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='userapp.userprofile')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='exercise.submission')),
            ],
        ),
    ]
