# Generated by Django 5.1.2 on 2024-11-08 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_onlineclass_capacity_onlineclass_entrance_code_and_more'),
        ('exercise', '0001_initial'),
        ('userapp', '0002_userprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='group_allowed',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='auto_score',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='manual_score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='code_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AddField(
            model_name='exercise',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='online_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='class.onlineclass'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grading',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grading',
            name='graded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grading',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='userapp.userprofile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='userapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ExerciseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_submitted', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'exercise')},
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
