# Generated by Django 5.1.2 on 2024-11-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classmembership',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='userapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='classmembership',
            unique_together={('online_class', 'user_profile')},
        ),
    ]
