# Generated by Django 5.1.2 on 2024-11-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_alter_classmembership_unique_together_and_more'),
        ('userapp', '0002_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='entrance_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='has_capacity_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='userapp.userprofile'),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='userapp.userprofile'),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='userapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='classmembership',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('mentor', 'Mentor')], max_length=10),
        ),
    ]
