# Generated by Django 5.1.2 on 2024-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_onlineclass_capacity_onlineclass_entrance_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
